# Generated by Django 3.2.4 on 2021-06-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='django_Pings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hosts', models.CharField(max_length=40)),
                ('Pings', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
