# Generated by Django 3.2.4 on 2021-06-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='django_Pings',
            fields=[
                ('idping', models.BigAutoField(primary_key=True, serialize=False)),
                ('Hosts', models.CharField(max_length=40)),
                ('Pings', models.CharField(max_length=100)),
                ('Data', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
